import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import React from "react";

const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: "BLOG",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Link href={'/'}>BLOG Home</Link>
        <SessionProvider session={session}>
          <main>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
